apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nimage-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - {{ template "ingress.host" . }}
      secretName: nfler-tls
  rules:
  - host: {{ template "ingress.host" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nimage-svc
            port:
              number: 4000